Repository AndyChhuon/SOEN390, pull requests merged in 2024-04, with the labels that each got.

#106 switch off localhost
  condo-management-app/hooks/useAuth.js
Labels: fix

#107 Code coverage with cypress + code coverage reports
  condo-management-app/.babelrc
  condo-management-app/.nyc_output/out.json
  condo-management-app/coverage/clover.xml
  condo-management-app/coverage/coverage-final.json
  condo-management-app/coverage/coverage-summary.json
  condo-management-app/coverage/lcov-report/condo-management-app/App.js.html
  condo-management-app/coverage/lcov-report/condo-management-app/hooks/index.html
  condo-management-app/coverage/lcov-report/condo-management-app/hooks/useAuth.js.html
  condo-management-app/coverage/lcov-report/condo-management-app/index.html
  condo-management-app/coverage/lcov-report/condo-management-app/navigator/bottomTabBar.js.html
  condo-management-app/coverage/lcov-report/condo-management-app/navigator/index.html
  condo-management-app/coverage/lcov-report/condo-management-app/screens/AppContent.js.html
  condo-management-app/coverage/lcov-report/condo-management-app/screens/index.html
  condo-management-app/coverage/lcov-report/condo-management-app/screens/myRentedProperties/index.html
  condo-management-app/coverage/lcov-report/condo-management-app/screens/myRentedProperties/myRentedProperties.js.html
  condo-management-app/coverage/lcov-report/condo-management-app/screens/rentPropertiesScreen/index.html
  condo-management-app/coverage/lcov-report/condo-management-app/screens/rentPropertiesScreen/rentPropertiesScreen.js.html
  condo-management-app/coverage/lcov-report/condo-management-app/screens/reservationScreen/index.html
  condo-management-app/coverage/lcov-report/condo-management-app/screens/reservationScreen/reservationScreen.js.html
  condo-management-app/coverage/lcov-report/index.html
  condo-management-app/coverage/lcov.info
  condo-management-app/package.json
Labels: Testing

#120 Added backend test for rent and reserving
  condo-backend/.eslintrc.js
  condo-backend/codeQuality.html
  condo-backend/coverage/clover.xml
  condo-backend/coverage/coverage-final.json
  condo-backend/coverage/lcov-report/index.html
  condo-backend/coverage/lcov-report/src/app.ts.html
  condo-backend/coverage/lcov-report/src/aws/aws.ts.html
  condo-backend/coverage/lcov-report/src/aws/index.html
  condo-backend/coverage/lcov-report/src/firebase/financialService.ts.html
  condo-backend/coverage/lcov-report/src/firebase/firebase.ts.html
  condo-backend/coverage/lcov-report/src/firebase/index.html
  condo-backend/coverage/lcov-report/src/firebase/propertyProfileService.ts.html
  condo-backend/coverage/lcov-report/src/firebase/rentingService.ts.html
  condo-backend/coverage/lcov-report/src/firebase/userService.ts.html
  condo-backend/coverage/lcov-report/src/index.html
  condo-backend/coverage/lcov-report/src/openai/chat.ts.html
  condo-backend/coverage/lcov-report/src/openai/index.html
  condo-backend/coverage/lcov-report/src/utils/index.html
  condo-backend/coverage/lcov-report/src/utils/utils.ts.html
  condo-backend/coverage/lcov.info
  condo-backend/src/app.ts
  condo-backend/src/firebase/firebase.ts
  condo-backend/src/firebase/rentingService.ts
  condo-backend/test/index.test.ts
Labels: Testing

#123 Backend fix
  condo-backend/src/firebase/userService.ts
Labels: bug

#125 added integration test
  condo-management-app/cypress/e2e/update_fees_of_property_spec.cy.ts
  condo-management-app/navigator/bottomTabBar.js
  condo-management-app/screens/financialSystem/financialSystemScreen.js
Labels: Testing

#126 Property Test
  condo-management-app/cypress/e2e/add_property.cy.ts
  condo-management-app/screens/propertyProfile/propertyProfileScreen.js
Labels: Testing

#130 Added folder for sprint 4
  Sprint-4-Deliverables/toRemove.txt
Labels: fix

#131 Adding Release Plan for Sprint #5
  Sprint-4-Deliverables/Release Plan for Sprint #5.pdf
Labels: documentation

#132 Delete Sprint-4-Deliverables/toRemove.txt
  Sprint-4-Deliverables/toRemove.txt
Labels: fix

#133 Added code style
  Sprint-4-Deliverables/Code style.pdf
Labels: documentation

#134 add bug report sprint 4
  Sprint-4-Deliverables/Bug report.pdf
Labels: documentation

#136 CMS-119 integration test request creation
  condo-backend/.gitignore
  condo-management-app/cypress/e2e/create_request_spec.cy.ts
  condo-management-app/screens/Request/ChatPage.js
  condo-management-app/screens/Request/RequestPage.js
Labels: Testing

#140 Testing documentation sprint 5
  Sprint-4-Deliverables/Testing Report Sprint 4.pdf
  Sprint-4-Deliverables/Testing plan for sprint 5.pdf
Labels: documentation, Testing
