Repository AndyChhuon/SOEN390, pull requests merged in 2024-05, with the labels that each got.

#150 Add backend frontend employee management
  condo-backend/src/app.ts
  condo-backend/src/firebase/employeeManagement.ts
  condo-backend/src/firebase/firebase.ts
  condo-backend/src/firebase/userService.ts
  condo-management-app/hooks/useAuth.js
  condo-management-app/navigator/bottomTabBar.js
  condo-management-app/package.json
  condo-management-app/screens/Components/Dropdown.js
  condo-management-app/screens/employeeManagement/employeeManagementScreen.js
  condo-management-app/screens/profile/profileScreen.js
Labels: User Story Task

#152 Add tests for employee management
  condo-backend/test/index.test.ts
Labels: Testing

#156 Add android apk
  README.md
Labels: User Story Task

#154 Integration testing
  condo-management-app/cypress/downloads/report.pdf
  condo-management-app/cypress/e2e/add_costs_and_generate_report_spec.cy.ts
  condo-management-app/cypress/e2e/add_property.cy.ts
  condo-management-app/cypress/e2e/make_a_reservation_spec.cy.ts
  condo-management-app/screens/financialSystem/financialSystemScreen.js
Labels: Testing

#158 Create deliverables folder and add testing report sprint 5
  Sprint-5-Deliverables/Testing Report Sprint 5.pdf
Labels: documentation, Testing

#159 Add files via upload
  Sprint-5-Deliverables/Sprint 1-5 Retrospectives.pdf
Labels: documentation

#161 Add bug report and code style docs
  Sprint-5-Deliverables/Bug_report_sprint_5.pdf
  Sprint-5-Deliverables/Code_style_sprint_5.pdf
Labels: documentation

#163 Added final report and presentation
  Sprint-5-Deliverables/Condo Management Final Presentation.pdf
  Sprint-5-Deliverables/Final Report - The Condo Management Company.pdf
Labels: documentation
