Repository AndyChhuon/SOEN390, pull requests merged in 2024-03, with the labels that each got.

#59 Added backend testing for CMS83 and CMS84
  condo-backend/coverage/clover.xml
  condo-backend/coverage/coverage-final.json
  condo-backend/coverage/lcov-report/base.css
  condo-backend/coverage/lcov-report/block-navigation.js
  condo-backend/coverage/lcov-report/favicon.png
  condo-backend/coverage/lcov-report/index.html
  condo-backend/coverage/lcov-report/prettify.css
  condo-backend/coverage/lcov-report/prettify.js
  condo-backend/coverage/lcov-report/sort-arrow-sprite.png
  condo-backend/coverage/lcov-report/sorter.js
  condo-backend/coverage/lcov-report/src/app.ts.html
  condo-backend/coverage/lcov-report/src/aws/aws.ts.html
  condo-backend/coverage/lcov-report/src/aws/index.html
  condo-backend/coverage/lcov-report/src/firebase/firebase.ts.html
  condo-backend/coverage/lcov-report/src/firebase/index.html
  condo-backend/coverage/lcov-report/src/firebase/propertyProfileService.ts.html
  condo-backend/coverage/lcov-report/src/firebase/userService.ts.html
  condo-backend/coverage/lcov-report/src/index.html
  condo-backend/coverage/lcov-report/src/utils/index.html
  condo-backend/coverage/lcov-report/src/utils/utils.ts.html
  condo-backend/coverage/lcov.info
  condo-backend/package.json
  condo-backend/src/app.ts
  condo-backend/src/aws/aws.ts
  condo-backend/test/index.test.ts
Labels: Testing

#63 Added testing plan for sprint 3
  Testing plan for sprint 3.pdf
Labels: documentation

#57 Update financialSystemScreen.js
  condo-management-app/screens/financialSystem/financialSystemScreen.js
Labels: User Story Task

#70 Added Testing Report
  Sprint-2-Deliverables/Testing Report Sprint 3 .pdf
Labels: documentation

#72 Sprint2 UI
  condo-management-app/assets/images/icons/condoimage.svg
  condo-management-app/constants/styles.js
  condo-management-app/navigator/bottomTabBar.js
  condo-management-app/package.json
  condo-management-app/screens/AppContent.js
  condo-management-app/screens/Components/Dropdown.js
  condo-management-app/screens/LandingPage/landingPage.js
  condo-management-app/screens/auth/image.png
  condo-management-app/screens/auth/image_2.png
  condo-management-app/screens/auth/image_3.png
  condo-management-app/screens/auth/loginScreen.js
  condo-management-app/screens/auth/signupScreen.js
  condo-management-app/screens/financialSystem/financialSystemScreen.js
  condo-management-app/screens/profile/profileScreen.js
  condo-management-app/screens/propertyPage/propertyPage.js
  condo-management-app/screens/propertyProfile/propertyProfileScreen.js
Labels: User Story Task

#74 Add jest and index.test.js
  Sprint-2-Deliverables/test
  condo-management-app/package.json
  condo-management-app/test/index.test.js
Labels: Testing

#78 add total to financial report
  condo-backend/src/firebase/financialService.ts
Labels: User Story Task

#79 Add backend tests for sprint 3
  condo-backend/coverage/clover.xml
  condo-backend/coverage/coverage-final.json
  condo-backend/coverage/lcov-report/index.html
  condo-backend/coverage/lcov-report/src/app.ts.html
  condo-backend/coverage/lcov-report/src/aws/aws.ts.html
  condo-backend/coverage/lcov-report/src/aws/index.html
  condo-backend/coverage/lcov-report/src/firebase/financialService.ts.html
  condo-backend/coverage/lcov-report/src/firebase/firebase.ts.html
  condo-backend/coverage/lcov-report/src/firebase/index.html
  condo-backend/coverage/lcov-report/src/firebase/propertyProfileService.ts.html
  condo-backend/coverage/lcov-report/src/firebase/userService.ts.html
  condo-backend/coverage/lcov-report/src/index.html
  condo-backend/coverage/lcov-report/src/openai/chat.ts.html
  condo-backend/coverage/lcov-report/src/openai/index.html
  condo-backend/coverage/lcov-report/src/utils/index.html
  condo-backend/coverage/lcov-report/src/utils/utils.ts.html
  condo-backend/coverage/lcov.info
  condo-backend/src/app.ts
  condo-backend/test/index.test.ts
Labels: Testing

#82 CMS-79 integration testing user auth
  condo-management-app/.nyc_output/out.json
  condo-management-app/coverage/clover.xml
  condo-management-app/coverage/coverage-final.json
  condo-management-app/coverage/coverage-summary.json
  condo-management-app/coverage/lcov-report/base.css
  condo-management-app/coverage/lcov-report/block-navigation.js
  condo-management-app/coverage/lcov-report/favicon.png
  condo-management-app/coverage/lcov-report/index.html
  condo-management-app/coverage/lcov-report/prettify.css
  condo-management-app/coverage/lcov-report/prettify.js
  condo-management-app/coverage/lcov-report/sort-arrow-sprite.png
  condo-management-app/coverage/lcov-report/sorter.js
  condo-management-app/coverage/lcov.info
  condo-management-app/cypress.config.ts
  condo-management-app/cypress/e2e/login_page_spec.cy.ts
  condo-management-app/cypress/e2e/signin_page_spec.cy.ts
  condo-management-app/cypress/e2e/spec.cy.ts
  condo-management-app/cypress/fixtures/example.json
  condo-management-app/cypress/support/commands.ts
  condo-management-app/cypress/support/e2e.ts
  condo-management-app/package.json
  condo-management-app/screens/auth/loginScreen.js
  condo-management-app/screens/auth/signupScreen.js
Labels: Testing

#83 Added eslint for code quality
  condo-backend/.eslintrc.js
  condo-backend/codeQuality.html
  condo-backend/coverage/clover.xml
  condo-backend/coverage/coverage-final.json
  condo-backend/coverage/lcov-report/index.html
  condo-backend/coverage/lcov-report/src/app.ts.html
  condo-backend/coverage/lcov-report/src/aws/aws.ts.html
  condo-backend/coverage/lcov-report/src/aws/index.html
  condo-backend/coverage/lcov-report/src/firebase/financialService.ts.html
  condo-backend/coverage/lcov-report/src/firebase/firebase.ts.html
  condo-backend/coverage/lcov-report/src/firebase/index.html
  condo-backend/coverage/lcov-report/src/firebase/propertyProfileService.ts.html
  condo-backend/coverage/lcov-report/src/firebase/userService.ts.html
  condo-backend/coverage/lcov-report/src/index.html
  condo-backend/coverage/lcov-report/src/openai/chat.ts.html
  condo-backend/coverage/lcov-report/src/openai/index.html
  condo-backend/coverage/lcov-report/src/utils/index.html
  condo-backend/coverage/lcov-report/src/utils/utils.ts.html
  condo-backend/coverage/lcov.info
  condo-backend/package.json
  condo-backend/src/app.ts
  condo-backend/src/aws/aws.ts
  condo-backend/src/firebase/financialService.ts
  condo-backend/src/firebase/firebase.ts
  condo-backend/src/firebase/propertyProfileService.ts
  condo-backend/src/firebase/userService.ts
  condo-backend/src/index.ts
  condo-backend/src/openai/chat.ts
  condo-backend/src/utils/utils.ts
  condo-backend/test/index.test.ts
Labels: documentation

#89 Added code style and quality doc
  Sprint-3-Deliverables/Code style & Code Quality.pdf
Labels: documentation

#87 Integration testing for profile editing
  condo-management-app/coverage/clover.xml
  condo-management-app/coverage/lcov-report/index.html
  condo-management-app/cypress/e2e/enter_And_Update_Info_spec.cy.ts
  condo-management-app/screens/profile/profileScreen.js
Labels: Testing

#85 UI fix ChatPage.js
  condo-management-app/screens/Request/ChatPage.js
Labels: fix

#91 Added testing report and plan
  Sprint-3-Deliverables/Testing Report Sprint 3.pdf
  Sprint-3-Deliverables/Testing plan for sprint 4.pdf
Labels: documentation, Testing

#92 Add User Stories and UI Prototype for the new sprint
  Sprint-3-Deliverables/User Stories and UI Prototypes.pdf
Labels: documentation

#95 Update README coding style
  README.md
Labels: documentation

#93 Added bug report document
  Sprint-3-Deliverables/Bug report.pdf
Labels: documentation

#96 Added SAD
  Sprint-3-Deliverables/Architecture Description Sprint 3.pdf
Labels: documentation

#101 Added slides used for Sprint 3 presentation
  Sprint-3-Deliverables/Presentation Sprint 3.pdf
Labels: documentation
